# Generated by Django 5.1.1 on 2024-10-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_subject_subjectmarks"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectmarks",
            unique_together={("student", "subject")},
        ),
    ]
